# Generated by Django 6.0.5 on 2026-06-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash on Delivery'), ('WALLET', 'Wallet Balance'), ('MOBILE_MONEY', 'Mobile Money')], default='CARD', max_length=20),
        ),
    ]
