# Generated by Django 6.0.7 on 2026-07-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Successful'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('REFUND_PENDING', 'Refund pending'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
    ]
