# Generated by Django 6.0.7 on 2026-07-31 11:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundries', '0013_laundry_changes_requested_at_laundry_reviewed_by_and_more'),
        ('ordering', '0014_order_currency_order_delivery_fee_and_more'),
        ('payments', '0006_alter_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('method', models.CharField(choices=[('BANK', 'Bank transfer'), ('MOMO', 'Mobile money'), ('PAYSTACK_TRANSFER', 'Paystack transfer'), ('MANUAL', 'Manual / cash')], default='MANUAL', max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laundry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='laundries.laundry')),
            ],
            options={
                'verbose_name': 'Payout',
                'verbose_name_plural': 'Payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('processor_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_payable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('PAID', 'Paid'), ('REVERSED', 'Reversed')], default='PENDING', max_length=20)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laundry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='laundries.laundry')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='ordering.order')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='payments.payout')),
            ],
            options={
                'verbose_name': 'Order settlement',
                'verbose_name_plural': 'Order settlements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['laundry', 'status'], name='payments_pa_laundry_cd423c_idx'),
        ),
        migrations.AddIndex(
            model_name='ordersettlement',
            index=models.Index(fields=['laundry', 'status'], name='payments_or_laundry_1c1685_idx'),
        ),
        migrations.AddIndex(
            model_name='ordersettlement',
            index=models.Index(fields=['status', 'created_at'], name='payments_or_status_16e2b0_idx'),
        ),
    ]
