# Generated by Django 6.0.7 on 2026-07-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payout_ordersettlement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersettlement',
            name='route',
            field=models.CharField(choices=[('PLATFORM', 'Collected by platform'), ('DIRECT', 'Settled directly')], default='PLATFORM', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='settled_directly',
            field=models.BooleanField(default=False),
        ),
    ]
