# Generated by Django 6.0.7 on 2026-07-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_ordersettlement_route_payment_settled_directly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersettlement',
            name='status',
            field=models.CharField(choices=[('HELD', 'Held until delivered'), ('PENDING', 'Ready to pay out'), ('SCHEDULED', 'Scheduled'), ('PAID', 'Paid'), ('REVERSED', 'Reversed')], default='PENDING', max_length=20),
        ),
    ]
