# Generated by Django 6.0.7 on 2026-07-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_ordersettlement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersettlement',
            name='release_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
