# Generated by Django 6.0.5 on 2026-09-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundries', '0017_laundry_payout_account_name_and_more'),
        ('payments', '0012_payment_amount_collected_payment_collected_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='paystack_transfer_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payout',
            name='recipient_code_used',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payout',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('WAITING_FOR_FUNDS', 'Waiting for funds'), ('REVERSED', 'Reversed')], default='DRAFT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_2b7eb1_idx'),
        ),
    ]
