# Generated by Django 6.0.7 on 2026-09-24 15:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0018_order_payment_method'),
        ('payments', '0013_payout_paystack_transfer_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('NOT_RECEIVED', 'I did not receive my order'), ('ITEMS_MISSING', 'Items are missing'), ('ITEMS_DAMAGED', 'Items are damaged'), ('POOR_QUALITY', 'Not cleaned properly'), ('OTHER', 'Something else')], max_length=20)),
                ('details', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('OPEN', 'Open — payment on hold'), ('RESOLVED_RELEASED', 'Resolved — paid to laundry'), ('RESOLVED_REFUNDED', 'Resolved — customer refunded'), ('MANUAL_REVIEW', 'Needs manual financial review')], db_index=True, default='OPEN', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='ordering.order')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_disputes', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_order_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order dispute',
                'verbose_name_plural': 'Order disputes',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('order',), name='one_open_dispute_per_order')],
            },
        ),
    ]
