# Generated by Django 6.0.5 on 2026-09-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_order_dispute'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersettlement',
            name='logistics_subsidy_deducted',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
