# Generated by Django 6.0.7 on 2026-09-27 14:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordering', '0020_order_logistics_nominal_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotificationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('NEW_ORDER', 'New order'), ('PAYMENT_CONFIRMED', 'Payment confirmed'), ('ORDER_CANCELLED', 'Order cancelled'), ('ORDER_REJECTED', 'Order rejected by laundry'), ('ORDER_RESCHEDULED', 'Order rescheduled'), ('PICKUP_LOCATION_CHANGED', 'Pickup location changed'), ('DELIVERY_LOCATION_CHANGED', 'Delivery location changed'), ('ORDER_PRICE_FINALIZED', 'Order price finalized')], db_index=True, max_length=32)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('payload', models.JSONField()),
                ('payload_version', models.PositiveSmallIntegerField(default=1)),
                ('environment', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notification_events', to='ordering.order')),
            ],
            options={
                'verbose_name': 'Admin notification event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminNotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], max_length=16)),
                ('recipient', models.CharField(max_length=20)),
                ('provider', models.CharField(max_length=32)),
                ('dedup_key', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENDING', 'Sending'), ('RETRY', 'Waiting to retry'), ('SUBMITTED', 'Submitted to provider'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered to handset'), ('UNDELIVERED', 'Not delivered (provider report)'), ('UNKNOWN', 'Unknown (possible duplicate risk)'), ('FAILED', 'Failed (needs config/provider fix)'), ('DEAD', 'Dead (retries exhausted or expired)')], db_index=True, default='PENDING', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_token', models.UUIDField(blank=True, null=True)),
                ('parts_total', models.PositiveSmallIntegerField(default=0)),
                ('parts_sent', models.PositiveSmallIntegerField(default=0)),
                ('estimated_segments', models.PositiveIntegerField(default=0)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=128)),
                ('last_error_class', models.CharField(blank=True, default='', max_length=40)),
                ('last_error_safe_message', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='admin_notifications.adminnotificationevent')),
            ],
            options={
                'verbose_name': 'Admin notification delivery',
                'verbose_name_plural': 'Admin notification deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminNotificationProviderMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part_index', models.PositiveSmallIntegerField()),
                ('provider', models.CharField(max_length=32)),
                ('provider_message_id', models.CharField(blank=True, max_length=128, null=True)),
                ('provider_status', models.CharField(blank=True, default='', max_length=24)),
                ('estimated_segments', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status_updated_at', models.DateTimeField(blank=True, null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_messages', to='admin_notifications.adminnotificationdelivery')),
            ],
            options={
                'ordering': ['part_index'],
            },
        ),
        migrations.AddIndex(
            model_name='adminnotificationevent',
            index=models.Index(fields=['order', 'event_type'], name='admin_notif_order_i_c77436_idx'),
        ),
        migrations.AddIndex(
            model_name='adminnotificationdelivery',
            index=models.Index(fields=['status', 'next_attempt_at'], name='admin_notif_status_388a42_idx'),
        ),
        migrations.AddConstraint(
            model_name='adminnotificationdelivery',
            constraint=models.UniqueConstraint(fields=('event', 'channel', 'recipient'), name='uniq_admin_notif_delivery_recipient'),
        ),
        migrations.AddConstraint(
            model_name='adminnotificationprovidermessage',
            constraint=models.UniqueConstraint(fields=('delivery', 'part_index'), name='uniq_admin_notif_part'),
        ),
        migrations.AddConstraint(
            model_name='adminnotificationprovidermessage',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_message_id'), name='uniq_admin_notif_provider_msg'),
        ),
    ]
