# Generated by Django 6.0.5 on 2026-09-25 16:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsPricingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pricing_enabled', models.BooleanField(default=False, help_text='Turn ON to activate dynamic pickup/delivery pricing. When OFF, mobile shows delivery is separate.')),
                ('pickup_price_per_km', models.DecimalField(decimal_places=2, default=2.5, help_text='Pickup price per kilometre in GHS.', max_digits=8)),
                ('delivery_price_per_km', models.DecimalField(decimal_places=2, default=3.0, help_text='Delivery price per kilometre in GHS.', max_digits=8)),
                ('pickup_base_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Optional base fee for pickup in GHS.', max_digits=8)),
                ('delivery_base_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Optional base fee for delivery in GHS.', max_digits=8)),
                ('pickup_min_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Optional minimum charge for pickup in GHS.', max_digits=8)),
                ('delivery_min_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Optional minimum charge for delivery in GHS.', max_digits=8)),
                ('max_service_distance_km', models.DecimalField(decimal_places=2, default=25.0, help_text='Maximum distance in km allowed for logistics service.', max_digits=6)),
                ('distance_rounding_precision', models.PositiveSmallIntegerField(default=1, help_text='Decimal places for rounding distance (e.g. 1 means 0.1 km / 100m).')),
                ('currency', models.CharField(default='GHS', editable=False, max_length=3)),
                ('effective_from', models.DateTimeField(help_text='When these rates take effect.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration profile is active.')),
                ('version', models.PositiveIntegerField(default=1, help_text='Monotonically increasing version identifier.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Logistics Pricing Configuration',
                'verbose_name_plural': 'Logistics Pricing Configurations',
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogisticsPricingAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('old_values', models.JSONField(default=dict)),
                ('new_values', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='logistics.logisticspricingconfig')),
            ],
            options={
                'verbose_name': 'Logistics Pricing Audit',
                'verbose_name_plural': 'Logistics Pricing Audits',
                'ordering': ['-changed_at'],
            },
        ),
    ]
