# Generated by Django 6.0.7 on 2026-09-25 18:34

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models



def seed_disabled_config(apps, schema_editor):
    """One row for the admin to edit. Pricing stays OFF until they switch it on."""
    from django.utils import timezone
    Config = apps.get_model('logistics', 'LogisticsPricingConfig')
    if not Config.objects.exists():
        Config.objects.create(pricing_enabled=False, is_active=True, effective_from=timezone.now(), version=1)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_logisticspricingconfig_logisticspricingaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticspricingconfig',
            name='minimum_billable_distance_km',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Legs shorter than this are billed as this distance (e.g. 1.00 bills a 400 m trip as 1 km).', max_digits=6),
        ),
        migrations.AddField(
            model_name='logisticspricingconfig',
            name='road_distance_factor',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Distance is measured in a straight line between the two map pins, then multiplied by this factor to approximate the road route. 1.00 bills the straight line; 1.30 adds 30%.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('3.00'))]),
        ),
        migrations.AlterField(
            model_name='logisticspricingconfig',
            name='effective_from',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When these rates take effect. The newest row already in effect is the one used.'),
        ),
        migrations.RunPython(seed_disabled_config, noop),
    ]
