# Generated by Django 6.0.7 on 2026-09-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_logisticspricingconfig_minimum_billable_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticspricingconfig',
            name='min_android_build',
            field=models.PositiveIntegerField(default=10, help_text='Lowest Android build (versionCode) allowed to book while pricing is ON.'),
        ),
        migrations.AddField(
            model_name='logisticspricingconfig',
            name='min_ios_build',
            field=models.PositiveIntegerField(default=10, help_text='Lowest iOS build number allowed to book while pricing is ON.'),
        ),
    ]
