# Generated by Django 6.0.2 on 2026-03-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_passwordresettoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresettoken",
            name="expires_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="token_hash",
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
