# Generated by Django 6.0.2 on 2026-05-08 19:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_passwordresettoken_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_family_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('device_id', models.CharField(db_index=True, max_length=128)),
                ('platform', models.CharField(blank=True, max_length=32)),
                ('app_version', models.CharField(blank=True, max_length=32)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('current_refresh_jti', models.CharField(blank=True, db_index=True, max_length=255)),
                ('current_refresh_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'device session',
                'verbose_name_plural': 'device sessions',
                'ordering': ['-last_used_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionRefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jti', models.CharField(db_index=True, max_length=255, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('replaced_by_jti', models.CharField(blank=True, max_length=255)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=64)),
                ('reuse_detected_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='users.devicesession')),
            ],
            options={
                'verbose_name': 'session refresh token',
                'verbose_name_plural': 'session refresh tokens',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.AddIndex(
            model_name='devicesession',
            index=models.Index(fields=['user', 'revoked_at'], name='users_devic_user_id_47297b_idx'),
        ),
        migrations.AddIndex(
            model_name='devicesession',
            index=models.Index(fields=['session_family_id', 'revoked_at'], name='users_devic_session_ed9cb6_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionrefreshtoken',
            index=models.Index(fields=['session', 'revoked_at'], name='users_sessi_session_a606bd_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionrefreshtoken',
            index=models.Index(fields=['session', 'expires_at'], name='users_sessi_session_faa0aa_idx'),
        ),
    ]
