# Generated by Django 6.0.5 on 2026-05-21 16:55

import laundries.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_devicesession_sessionrefreshtoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[laundries.utils.validators.validate_file_upload], verbose_name='avatar'),
        ),
    ]
