# Generated by Django 6.0.5 on 2026-06-12 09:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_clerk_social_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='clerk_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='clerk_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='clerk_status',
            field=models.CharField(blank=True, db_index=True, default='unsynced', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='clerk_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_clerk_sign_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_clerk_sync',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.CreateModel(
            name='ClerkWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('svix_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('clerk_user_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], db_index=True, default='PROCESSING', max_length=16)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Clerk Webhook Event',
                'verbose_name_plural': 'Clerk Webhook Events',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['event_type', 'received_at'], name='users_clerk_event_t_4a0783_idx'), models.Index(fields=['clerk_user_id', 'received_at'], name='users_clerk_clerk_u_1e77e0_idx'), models.Index(fields=['status', 'received_at'], name='users_clerk_status_8a694e_idx')],
            },
        ),
    ]
