[pytest]
DJANGO_SETTINGS_MODULE = config.test_settings
python_files = tests.py test_*.py *_tests.py
pythonpath = . tests
addopts = --reuse-db -p no:doctest --import-mode=importlib
norecursedirs = venv tmp .venv .git .pytest_cache
