# Generated by Django 6.0.6 on 2026-06-25 16:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(db_index=True, max_length=64)),
                ('session_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('device_id', models.CharField(blank=True, default='', max_length=128)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web'), ('server', 'Server'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('os_version', models.CharField(blank=True, default='', max_length=32)),
                ('app_version', models.CharField(blank=True, default='', max_length=32)),
                ('screen_name', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analytics Event',
                'verbose_name_plural': 'Analytics Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_name', 'created_at'], name='analytics_a_event_n_e2acee_idx'), models.Index(fields=['user', 'created_at'], name='analytics_a_user_id_ecb128_idx'), models.Index(fields=['session_id', 'created_at'], name='analytics_a_session_533ea7_idx')],
            },
        ),
    ]
