# Generated by Django 6.0.2 on 2026-03-10 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ordering", "0005_remove_launderableitem_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="launderableitem",
            name="base_price",
        ),
        migrations.RemoveField(
            model_name="launderableitem",
            name="supported_services",
        ),
    ]
