# Generated by Django 6.0.2 on 2026-03-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0009_migrate_dual_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
