# Generated by Django 6.0.5 on 2026-05-21

import laundries.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0010_add_gps_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launderableitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/', validators=[laundries.utils.validators.validate_file_upload]),
        ),
    ]
