# Generated by Django 6.0.4 on 2026-06-10 22:25
#
# This migration sets db_column='final_price' on Order.total_amount, i.e. it
# renames the DB column total_amount -> final_price.
#
# Some databases already had this column renamed by an earlier (since-removed)
# migration history (e.g. the old `0012_rename_total_amount_order_final_price`).
# On those databases the column is already `final_price` and a second rename
# fails with "column total_amount does not exist". A fresh database, on the
# other hand, still has the `total_amount` column and DOES need the rename.
#
# We therefore split state from database: the model-state change is applied
# unconditionally, while the physical rename only runs when `total_amount` still
# exists (and `final_price` does not yet). This is idempotent and works on both
# already-migrated and fresh databases, across PostgreSQL and SQLite.

from django.db import migrations, models


def _columns(schema_editor, table):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        return {
            col.name
            for col in connection.introspection.get_table_description(cursor, table)
        }


def _execute_sql(schema_editor, sql_string):
    schema_editor.execute(sql_string)


def rename_total_amount_to_final_price(apps, schema_editor):
    table = 'ordering_order'
    columns = _columns(schema_editor, table)
    if 'total_amount' in columns and 'final_price' not in columns:
        qn = schema_editor.quote_name
        sql_string = 'ALTER TABLE %s RENAME COLUMN %s TO %s' % (
            qn(table), qn('total_amount'), qn('final_price')
        )
        _execute_sql(schema_editor, sql_string)


def rename_final_price_to_total_amount(apps, schema_editor):
    table = 'ordering_order'
    columns = _columns(schema_editor, table)
    if 'final_price' in columns and 'total_amount' not in columns:
        qn = schema_editor.quote_name
        sql_string = 'ALTER TABLE %s RENAME COLUMN %s TO %s' % (
            qn(table), qn('final_price'), qn('total_amount')
        )
        _execute_sql(schema_editor, sql_string)


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0011_alter_launderableitem_image'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='order',
                    name='total_amount',
                    field=models.DecimalField(
                        db_column='final_price',
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    rename_total_amount_to_final_price,
                    rename_final_price_to_total_amount,
                ),
            ],
        ),
    ]
