# Generated by Django 6.0.4 on 2026-06-16 18:43
#
# This migration alters 'pricing_method' and 'estimated_price' columns in the 'ordering_order' table
# to be nullable if they exist in the database.

from django.db import migrations

def make_columns_nullable(apps, schema_editor):
    db_table = 'ordering_order'
    connection = schema_editor.connection
    if connection.vendor != 'postgresql':
        return
    with connection.cursor() as cursor:
        # Get all columns for ordering_order
        columns = [col.name for col in connection.introspection.get_table_description(cursor, db_table)]
        
        # Check and alter pricing_method
        if 'pricing_method' in columns:
            cursor.execute(f"ALTER TABLE {db_table} ALTER COLUMN pricing_method DROP NOT NULL")
            
        # Check and alter estimated_price
        if 'estimated_price' in columns:
            cursor.execute(f"ALTER TABLE {db_table} ALTER COLUMN estimated_price DROP NOT NULL")

def make_columns_not_nullable(apps, schema_editor):
    # Reverse operation (no-op or safety logic since these are orphan columns)
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0012_alter_order_total_amount'),
    ]

    operations = [
        migrations.RunPython(
            make_columns_nullable,
            reverse_code=make_columns_not_nullable,
            elidable=True
        ),
    ]
