# Generated by Django 6.0.7 on 2026-07-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0014_order_currency_order_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_confirmed_by_code',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='handover_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
