# Generated by Django 6.0.7 on 2026-08-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0016_order_snapshot_db_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pricing_mode',
            field=models.CharField(choices=[('BY_ITEM', 'By item'), ('BY_WEIGHT', 'By weight'), ('CUSTOM_QUOTE', 'Pay after quote')], default='BY_ITEM', max_length=20),
        ),
        migrations.RunSQL(
            # The deployed backend predates this column and writes orders
            # without naming it. NOT NULL with no database default would reject
            # those inserts during a rolling deploy. See ordering/0016.
            sql='ALTER TABLE "ordering_order" ALTER COLUMN "pricing_mode" SET DEFAULT \'BY_ITEM\';',
            reverse_sql='ALTER TABLE "ordering_order" ALTER COLUMN "pricing_mode" DROP DEFAULT;',
        ),
    ]
