# Generated by Django 6.0.5 on 2026-08-13 15:56

from django.db import migrations, models


def copy_payment_method(apps, schema_editor):
    Order = apps.get_model('ordering', 'Order')
    for method in ('CARD', 'BANK_TRANSFER', 'CASH'):
        Order.objects.filter(payment__payment_method=method).update(payment_method=method)


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0017_order_estimated_weight_kg_order_pricing_mode'),
        ('payments', '0011_settlement_db_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Paystack'), ('BANK_TRANSFER', 'Bank transfer'), ('CASH', 'Cash on delivery')], default='CARD', max_length=20),
        ),
        migrations.RunPython(copy_payment_method, migrations.RunPython.noop),
    ]
