# Generated by Django 6.0.7 on 2026-09-25 18:34

from django.db import migrations, models



def platform_to_simame(apps, schema_editor):
    Order = apps.get_model('ordering', 'Order')
    Order.objects.filter(promo_funding_source='PLATFORM').update(promo_funding_source='SIMAME')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0019_order_delivery_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='logistics_nominal_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='nominal_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='nominal_pickup_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_scope',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.RunPython(platform_to_simame, noop),
    ]
