# Generated by Django 6.0.5 on 2026-10-03 04:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundries', '0021_laundry_laundries_l_status_95998a_idx_and_more'),
        ('ordering', '0020_order_logistics_nominal_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='ordering_or_user_id_d3e320_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['laundry', '-created_at'], name='ordering_or_laundry_7c71fc_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['laundry', 'status', 'payment_status'], name='ordering_or_laundry_c352c9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='ordering_or_status_07cbc6_idx'),
        ),
    ]
