# Generated by Django 6.0.5 on 2026-05-21

import laundries.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_pushdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='image',
            field=models.ImageField(upload_to='special_offers/', validators=[laundries.utils.validators.validate_file_upload], verbose_name='image'),
        ),
    ]
