# Generated by Django 6.0.4 on 2026-06-11 10:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_specialoffer_image'),
        ('ordering', '0012_alter_order_total_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_email', models.CharField(blank=True, default='', max_length=254)),
                ('action', models.CharField(choices=[('ADMIN_SEARCH', 'Admin Search'), ('USER_ROLE_CHANGED', 'User Role Changed'), ('USER_EDITED', 'User Edited'), ('LAUNDRY_APPROVED', 'Laundry Approved'), ('LAUNDRY_REJECTED', 'Laundry Rejected'), ('ORDER_STATUS_CHANGED', 'Order Status Changed'), ('PAYMENT_ACTION', 'Payment Action'), ('COUPON_CREATED', 'Coupon Created'), ('NOTIFICATION_DISMISSED', 'Notification Dismissed'), ('PERMISSION_DENIED', 'Permission Denied'), ('SECURITY_EVENT', 'Security Event')], db_index=True, max_length=40)),
                ('target_type', models.CharField(blank=True, db_index=True, default='', max_length=60)),
                ('target_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('target_repr', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='notification',
            name='audience',
            field=models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin')], db_index=True, default='USER', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='notification',
            name='dedup_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['audience', 'is_read', 'created_at'], name='marketplace_audienc_e8bfee_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['category'], name='marketplace_categor_0e61ed_idx'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'created_at'], name='marketplace_action_241c03_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor', 'created_at'], name='marketplace_actor_i_479d24_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_type', 'target_id'], name='marketplace_target__e71d60_idx'),
        ),
    ]
