# Generated by Django 6.0.6 on 2026-06-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_legal_cms'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushdevice',
            name='web_auth',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pushdevice',
            name='web_endpoint',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pushdevice',
            name='web_p256dh',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
