# Generated by Django 6.0.6 on 2026-06-24 16:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_pushdevice_web_auth_pushdevice_web_endpoint_and_more'),
        ('users', '0013_user_auth_provider_user_clerk_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notification_preference', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('push_enabled', models.BooleanField(default=True)),
                ('order_updates', models.BooleanField(default=True)),
                ('payment_updates', models.BooleanField(default=True)),
                ('promotions', models.BooleanField(default=True)),
                ('campaigns', models.BooleanField(default=True)),
                ('quiet_hours_start', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quiet_hours_end', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('segment', models.CharField(choices=[('ALL', 'All users'), ('INACTIVE', 'Inactive users'), ('PENDING_ORDERS', 'Users with pending orders'), ('UNPAID', 'Users with unpaid orders'), ('PROMO_OPT_IN', 'Users opted into promotions'), ('ABANDONED_BOOKING', 'Users with abandoned bookings')], default='ALL', max_length=30)),
                ('segment_params', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('action_url', models.CharField(blank=True, default='', max_length=500)),
                ('notification_type', models.CharField(choices=[('ORDER', 'Order Update'), ('SYSTEM', 'System Message'), ('PROMO', 'Promotion')], default='PROMO', max_length=20)),
                ('category', models.CharField(default='CAMPAIGN', max_length=40)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], db_index=True, default='DRAFT', max_length=12)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('recipients_count', models.PositiveIntegerField(default=0)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Campaign',
                'verbose_name_plural': 'Notification Campaigns',
                'ordering': ['-created_at'],
            },
        ),
    ]
