# Generated by Django 6.0.6 on 2026-06-25 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_notificationpreference_notificationcampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='marketplace.notificationcampaign'),
        ),
        migrations.AddField(
            model_name='notification',
            name='clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='push_status',
            field=models.CharField(choices=[('NONE', 'No push'), ('PENDING', 'Queued'), ('SENT', 'Sent to Expo'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], db_index=True, default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='clicked_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='failed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='opened_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='notificationcampaign',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationcampaign',
            name='segment',
            field=models.CharField(choices=[('ALL', 'All users'), ('ACTIVE', 'Active users'), ('INACTIVE', 'Inactive users'), ('PENDING_ORDERS', 'Users with pending orders'), ('UNPAID', 'Users with unpaid orders'), ('PROMO_OPT_IN', 'Users opted into promotions'), ('ABANDONED_BOOKING', 'Users with abandoned bookings'), ('REFERRAL', 'Users who referred others'), ('NEVER_ORDERED', 'Users who never ordered'), ('CUSTOM', 'Custom (explicit user ids)')], default='ALL', max_length=30),
        ),
    ]
