# Generated by Django 6.0.6 on 2026-06-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_notification_campaign_notification_clicked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='conversion_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='promo_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='converted_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='promo_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='revenue_generated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='referrals',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='weekly_tips',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationcampaign',
            name='segment',
            field=models.CharField(choices=[('ALL', 'All users'), ('ACTIVE', 'Active users'), ('INACTIVE', 'Inactive users'), ('PENDING_ORDERS', 'Users with pending orders'), ('UNPAID', 'Users with unpaid orders'), ('PROMO_OPT_IN', 'Users opted into promotions'), ('ABANDONED_BOOKING', 'Users with abandoned bookings'), ('REFERRAL', 'Users who referred others'), ('NEVER_ORDERED', 'Users who never ordered'), ('CITY', 'Users in a city'), ('CUSTOM', 'Custom (explicit user ids)')], default='ALL', max_length=30),
        ),
    ]
