# Generated by Django 6.0.7 on 2026-07-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_notification_conversion_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('ADMIN_SEARCH', 'Admin Search'), ('USER_ROLE_CHANGED', 'User Role Changed'), ('USER_EDITED', 'User Edited'), ('LAUNDRY_APPROVED', 'Laundry Approved'), ('LAUNDRY_REJECTED', 'Laundry Rejected'), ('LAUNDRY_CHANGES_REQUESTED', 'Laundry Changes Requested'), ('LAUNDRY_SUSPENDED', 'Laundry Suspended'), ('LAUNDRY_RESUBMITTED', 'Laundry Resubmitted'), ('ORDER_STATUS_CHANGED', 'Order Status Changed'), ('PAYMENT_ACTION', 'Payment Action'), ('COUPON_CREATED', 'Coupon Created'), ('NOTIFICATION_DISMISSED', 'Notification Dismissed'), ('LEGAL_DOCUMENT_CREATED', 'Legal Document Created'), ('LEGAL_DOCUMENT_UPDATED', 'Legal Document Updated'), ('LEGAL_DOCUMENT_PUBLISHED', 'Legal Document Published'), ('LEGAL_DOCUMENT_ARCHIVED', 'Legal Document Archived'), ('LEGAL_DOCUMENT_ROLLED_BACK', 'Legal Document Rolled Back'), ('LEGAL_ACCEPTANCE_RECORDED', 'Legal Acceptance Recorded'), ('PERMISSION_DENIED', 'Permission Denied'), ('SECURITY_EVENT', 'Security Event')], db_index=True, max_length=40),
        ),
    ]
