# Generated by Django 6.0.7 on 2026-07-29 09:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_alter_auditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('fingerprint', models.CharField(max_length=64)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, default='application/json', max_length=100)),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Idempotency Record',
                'verbose_name_plural': 'Idempotency Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
