# Generated by Django 6.0.5 on 2026-08-25 18:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_idempotencyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='push_status',
            field=models.CharField(choices=[('NONE', 'No push'), ('PENDING', 'Queued'), ('SENT', 'Sent to Expo'), ('DELIVERED', 'Delivered'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], db_index=True, default='NONE', max_length=10),
        ),
        migrations.CreateModel(
            name='PushDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('TICKET_OK', 'Ticket accepted'), ('TICKET_ERROR', 'Ticket rejected'), ('RECEIPT_OK', 'Receipt delivered'), ('RECEIPT_ERROR', 'Receipt failed')], db_index=True, max_length=20)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('receipt_payload', models.JSONField(blank=True, default=dict)),
                ('receipt_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_deliveries', to='marketplace.pushdevice')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_deliveries', to='marketplace.notification')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['notification', 'status'], name='marketplace_notific_1c45f8_idx'), models.Index(fields=['status', 'created_at'], name='marketplace_status_800ad2_idx')],
            },
        ),
    ]
