# Generated by Django 6.0.5 on 2026-08-25 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_alter_notification_push_status_pushdelivery'),
        ('ordering', '0018_order_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pushdevice',
            name='marketplace_user_id_b69260_idx',
        ),
        migrations.RemoveIndex(
            model_name='pushdevice',
            name='marketplace_device__142477_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='push_last_queued_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='pushdelivery',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pushdevice',
            name='environment',
            field=models.CharField(choices=[('staging', 'Staging'), ('production', 'Production')], db_index=True, default='production', max_length=12),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='pushdevice',
            index=models.Index(fields=['user', 'environment', 'is_active'], name='marketplace_user_id_45af4b_idx'),
        ),
        migrations.AddIndex(
            model_name='pushdevice',
            index=models.Index(fields=['device_id', 'environment'], name='marketplace_device__daa558_idx'),
        ),
        migrations.AlterField(
            model_name='pushdevice',
            name='environment',
            field=models.CharField(choices=[('staging', 'Staging'), ('production', 'Production')], db_index=True, default='staging', max_length=12),
        ),
    ]
