# Generated by Django 6.0.5 on 2026-08-25 19:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_remove_pushdevice_marketplace_user_id_b69260_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEventClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('audience', models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin')], max_length=10)),
                ('dedup_key', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_claim', to='marketplace.notification')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_event_claims', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
