# Generated by Django 6.0.5 on 2026-10-03 04:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_notificationeventclaim'),
        ('ordering', '0021_order_ordering_or_user_id_d3e320_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'audience', '-created_at'], name='marketplace_user_id_a632d9_idx'),
        ),
    ]
