# Generated by Django 6.0.7 on 2026-10-03 19:04

from django.db import migrations, models

MARKETING_TOGGLES = ('promotions', 'campaigns', 'referrals', 'weekly_tips')


def clear_marketing_opt_ins(apps, schema_editor):
    # Existing rows hold the old opt-out defaults (the app also synced its
    # own all-on defaults), so none is an explicit opt-in. App Store Guideline
    # 4.5.4 needs one before any promotional push. Order and payment updates
    # are untouched; customers re-enable marketing in Notification settings.
    NotificationPreference = apps.get_model('marketplace', 'NotificationPreference')
    NotificationPreference.objects.update(**{toggle: False for toggle in MARKETING_TOGGLES})


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_notification_marketplace_user_id_a632d9_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='campaigns',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='promotions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='referrals',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='weekly_tips',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(clear_marketing_opt_ins, migrations.RunPython.noop),
    ]
