"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
# pyre-ignore[import]
import dj_database_url

# pyre-ignore[import]
import sentry_sdk
# pyre-ignore[import]
from sentry_sdk.integrations.django import DjangoIntegration
# pyre-ignore[import]
from sentry_sdk.integrations.celery import CeleryIntegration
# pyre-ignore[missing-module]
from dotenv import load_dotenv
from config.redaction import redact_value

BASE_DIR = Path(__file__).resolve().parent.parent
if (BASE_DIR / '.env').exists():
    load_dotenv(BASE_DIR / '.env', override=False)


def _parse_csv_env(name: str, default: str = '') -> list[str]:
    raw = os.getenv(name, default)
    return [item.strip() for item in raw.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured('SECRET_KEY must be set.')
if not DEBUG and len(SECRET_KEY) < 50:
    raise ImproperlyConfigured('Production SECRET_KEY must be at least 50 characters.')

ALLOWED_HOSTS = [host for host in _parse_csv_env('ALLOWED_HOSTS', 'localhost,127.0.0.1') if host != '*']
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['localhost'] if DEBUG else []

#
AUTH_USER_MODEL = 'users.User'


# Application definition

# Check if PostGIS should be enabled (for production)
USE_POSTGIS = os.getenv('USE_POSTGIS', 'False') == 'True'

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.import_export',
    'unfold.contrib.guardian',
    'unfold.contrib.simple_history',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'django.contrib.postgres',

    'rest_framework',
    'drf_spectacular',
    'corsheaders',
    'cloudinary',
    'rest_framework_simplejwt.token_blacklist',
]

# Add GIS support only if USE_POSTGIS is enabled
if USE_POSTGIS:
    INSTALLED_APPS.append('django.contrib.gis')

INSTALLED_APPS += [
    'users',
    'marketplace',
    'ordering',
    'logistics',
    'payments',
    'laundries',
    'django_celery_results',
]

MIDDLEWARE = [
    'laundries.middleware.JSONErrorMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'config.middleware.security.SecurityHeadersMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'config.middleware.idempotency.IdempotencyMiddleware',
    'config.middleware.deactivation.DeactivationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'config.middleware.request_id.RequestIDMiddleware',
]

# Security Settings
DEBUG = os.getenv('DEBUG', 'False') == 'True'        

if not DEBUG:    
    # SSL/HTTPS
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # HSTS
    SECURE_HSTS_SECONDS = 31536000 # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Misc
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True

# Data limits
DATA_UPLOAD_MAX_MEMORY_SIZE = 2621440 # 2.5MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440 # 2.5MB

# CORS configuration
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Only allow all in dev mode
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:3000').split(',')
    if origin.strip()
]
CORS_ALLOW_CREDENTIALS = True

# CSRF Trusted Origins (required for Django 4.0+)
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost:3000').split(',')
    if origin.strip()
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Determine database scheme based on USE_POSTGIS
db_scheme = 'postgis' if USE_POSTGIS else 'postgres'
default_db_url = f"{db_scheme}://{os.getenv('DB_USER', 'postgres')}:{os.getenv('DB_PASSWORD', 'postgres')}@{os.getenv('DB_HOST', 'localhost')}:{os.getenv('DB_PORT', '5432')}/{os.getenv('DB_NAME', 'connect_db')}"

DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL', default_db_url),
        conn_max_age=600,
        ssl_require=not DEBUG
    )
}

# Set the appropriate database engine
if USE_POSTGIS:
    DATABASES['default']['ENGINE'] = 'django.contrib.gis.db.backends.postgis'
else:
    DATABASES['default']['ENGINE'] = 'django.db.backends.postgresql'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = os.getenv('STATIC_URL', '/static/')
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# Cloudinary Configuration
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}

# Django 4.2+ Storage Configuration
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Use Cloudinary in production or if credentials are found
if not DEBUG or os.getenv('CLOUDINARY_CLOUD_NAME'):
    STORAGES["default"] = {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    }

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'laundries.renderers.StandardResponseRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ) if DEBUG else (
        'laundries.renderers.StandardResponseRenderer',
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'config.exception_handler.custom_exception_handler',
    'DEFAULT_THROTTLE_CLASSES': [
        'config.throttling.BurstUserThrottle',
        'config.throttling.SustainedUserThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'burst_user': os.getenv('THROTTLE_BURST_USER', '60/minute'),
        'sustained_user': os.getenv('THROTTLE_SUSTAINED_USER', '1000/day'),
        'review': os.getenv('THROTTLE_REVIEW', '5/hour'),
        'feedback': os.getenv('THROTTLE_FEEDBACK', '3/hour'),
        'legal_public': os.getenv('THROTTLE_LEGAL_PUBLIC', '300/hour'),
        'anon': os.getenv('THROTTLE_ANON', '100/day'),
        'auth_login_ip': os.getenv('THROTTLE_AUTH_LOGIN_IP', '10/minute'),
        'auth_login_account': os.getenv('THROTTLE_AUTH_LOGIN_ACCOUNT', '5/minute'),
        'auth_register_ip': os.getenv('THROTTLE_AUTH_REGISTER_IP', '10/hour'),
        'auth_register_account': os.getenv('THROTTLE_AUTH_REGISTER_ACCOUNT', '3/hour'),
        'auth_refresh_ip': os.getenv('THROTTLE_AUTH_REFRESH_IP', '20/minute'),
        'password_reset_ip': os.getenv('THROTTLE_PASSWORD_RESET_IP', '5/hour'),
        'password_reset_account': os.getenv('THROTTLE_PASSWORD_RESET_ACCOUNT', '3/hour'),
        'reset_password_ip': os.getenv('THROTTLE_RESET_PASSWORD_IP', '10/hour'),
        'payment_create': os.getenv('THROTTLE_PAYMENT_CREATE', '10/hour'),
        'admin_search': os.getenv('THROTTLE_ADMIN_SEARCH', '120/minute'),
    },
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Connect Laundry API',
    'DESCRIPTION': 'API documentation for Connect Laundry marketplace.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_PATCH': True,
    'COMPONENT_SPLIT_REQUEST': True,
    'ENUM_NAME_OVERRIDES': {
        'LaundryApprovalStatusEnum': [
            ('PENDING', 'Pending'),
            ('APPROVED', 'Approved'),
            ('REJECTED', 'Rejected'),
            ('SUSPENDED', 'Suspended'),
        ],
        'OrderStatusEnum': [
            ('PENDING', 'Pending'),
            ('CONFIRMED', 'Confirmed'),
            ('REJECTED', 'Rejected'),
            ('PICKED_UP', 'Picked Up'),
            ('IN_PROCESS', 'In Process'),
            ('OUT_FOR_DELIVERY', 'Out for Delivery'),
            ('DELIVERED', 'Delivered'),
            ('COMPLETED', 'Completed'),
            ('CANCELLED', 'Cancelled'),
        ],
    },
}



USE_REDIS_CACHE = os.getenv('USE_REDIS_CACHE', 'False' if DEBUG else 'True') == 'True'
CACHE_LOCATION = os.getenv('REDIS_URL') or os.getenv('CELERY_BROKER_URL', '')
if USE_REDIS_CACHE and (CACHE_LOCATION.startswith('redis://') or CACHE_LOCATION.startswith('rediss://')):
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': CACHE_LOCATION,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                # Fail open: if Redis is unreachable, cache reads return the
                # default (None) and writes no-op instead of raising. This keeps
                # the API (and throttling, which is cache-backed) serving during
                # a Redis outage rather than returning 500 on every request.
                'IGNORE_EXCEPTIONS': True,
            },
        }
    }
    # Surface ignored cache errors in logs so outages remain observable.
    DJANGO_REDIS_LOG_IGNORED_EXCEPTIONS = True
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'connect-auth-cache',
        }
    }

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv('JWT_ACCESS_TOKEN_MINUTES', 10))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('JWT_REFRESH_TOKEN_DAYS', 14))),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'CHECK_REVOKE_TOKEN': True,
    'REVOKE_TOKEN_CLAIM': 'hash_password',
}

# Celery Configuration
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/1')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'django-db')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_ALWAYS_EAGER = DEBUG


# Email Settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

# Password Reset Settings
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'Connect Laundry <noreply@connectlaundry.com>')
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000' if DEBUG else 'https://app.connectlaundry.com')
PASSWORD_RESET_TOKEN_EXPIRY_HOURS = int(os.getenv('PASSWORD_RESET_TOKEN_EXPIRY_HOURS', 1))


# DEBUG = False
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True

# --- Observability ---


def _before_send_sentry(event, hint):
    event = redact_value(event)
    if isinstance(event, dict):
        request = event.get('request')
        if isinstance(request, dict):
            request.pop('data', None)
            request.pop('cookies', None)
            request.pop('headers', None)
            request.pop('env', None)
        user = event.get('user')
        if isinstance(user, dict):
            for field in ('email', 'ip_address', 'username', 'phone'):
                if field in user:
                    user[field] = '[REDACTED]'
    return event


SENTRY_DSN = os.getenv('SENTRY_DSN')
SENTRY_TRACES_SAMPLE_RATE = float(os.getenv('SENTRY_TRACES_SAMPLE_RATE', '1.0' if DEBUG else '0.05'))
if (
    SENTRY_DSN
    and SENTRY_DSN.startswith('http')
    and 'your_real_dsn' not in SENTRY_DSN
    and os.getenv('DISABLE_SENTRY', 'False') != 'True'
):
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            CeleryIntegration(),
        ],
        traces_sample_rate=SENTRY_TRACES_SAMPLE_RATE,
        send_default_pii=False,
        before_send=_before_send_sentry,
    )

LOGGING_LEVEL = os.getenv('DJANGO_LOG_LEVEL', 'INFO')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {
            '()': 'config.logging_formatters.CustomJsonFormatter',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'json',
        },
    },
    'loggers': {
        '': { # Root logger
            'handlers': ['console'],
            'level': LOGGING_LEVEL,            
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'WARNING',
            'propagate': False,
        },
    },
}

# Database Slow Query Tracking (Free tool: Native logging)
# Requires SQL_DEBUG_THRESHOLD env var (e.g. 0.2 for 200ms)
SQL_DEBUG_THRESHOLD = float(os.getenv('SQL_DEBUG_THRESHOLD', '0.2'))

# Celery Reliability
CELERY_MAX_RETRIES = int(os.getenv('CELERY_MAX_RETRIES', 5))
CELERY_RETRY_DELAY = int(os.getenv('CELERY_RETRY_DELAY', 10))

# Paystack Configuration
PAYSTACK_SECRET_KEY = os.getenv('PAYSTACK_SECRET_KEY')
PAYSTACK_PUBLIC_KEY = os.getenv('PAYSTACK_PUBLIC_KEY')
PAYSTACK_CALLBACK_URL = os.getenv('PAYSTACK_CALLBACK_URL')
PAYMENT_CURRENCY = os.getenv('PAYMENT_CURRENCY', 'GHS').upper()
EXPO_PUSH_ENABLED = os.getenv('EXPO_PUSH_ENABLED', 'False' if DEBUG else 'True') == 'True'

# Financial Settings
TAX_RATE = float(os.getenv('TAX_RATE', '0.07')) # Default 7%
DELIVERY_FEE_BASE = float(os.getenv('DELIVERY_FEE_BASE', '10.00')) # Default 10 GHS
PLATFORM_FEE_RATE = float(os.getenv('PLATFORM_FEE_RATE', '0.05')) # Default 5% commission

# Unfold Admin Configuration
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.templatetags.static import static as _static

UNFOLD = {
    "SITE_TITLE": "Connect Laundry Admin",
    "SITE_HEADER": "Connect Laundry",
    "SITE_URL": "/",
    "SITE_SYMBOL": "local_laundry_service",
    "DASHBOARD_CALLBACK": "config.admin_dashboard.dashboard_callback",
    # Admin Operations Center UI (global ⌘K search + notification bell).
    "STYLES": [lambda request: _static("admin_ops/admin_ops.css")],
    "SCRIPTS": [lambda request: _static("admin_ops/admin_ops.js")],
    "SEARCH": {
        "users.user": ["email", "first_name", "last_name"],
        "ordering.order": ["order_no", "user__email"],
        "laundries.laundry": ["name", "address"],
        "payments.payment": ["transaction_reference", "paystack_reference"],
    },
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "THEME": "light",
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "200": "233 213 255",
            "300": "216 180 254",
            "400": "192 132 252",
            "500": "168 85 247",
            "600": "147 51 234",
            "700": "126 34 206",
            "800": "107 33 168",
            "900": "88 28 135",
            "950": "59 7 100",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Operations"),
                "separator": True,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                    {
                        "title": _("Orders"),
                        "icon": "shopping_cart",
                        "link": reverse_lazy("admin:ordering_order_changelist"),
                    },
                    {
                        "title": _("Laundries"),
                        "icon": "store",
                        "link": reverse_lazy("admin:laundries_laundry_changelist"),
                    },
                ],
            },
            {
                "title": _("Users & Security"),
                "separator": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "people",
                        "link": reverse_lazy("admin:users_user_changelist"),
                    },
                    {
                        "title": _("Sessions"),
                        "icon": "devices",
                        "link": reverse_lazy("admin:users_devicesession_changelist"),
                    },
                ],
            },
            {
                "title": _("Finance"),
                "separator": True,
                "items": [
                    {
                        "title": _("Payments"),
                        "icon": "payments",
                        "link": reverse_lazy("admin:payments_payment_changelist"),
                    },
                ],
            },
        ],
    },
}
