# Generated by Django 6.0.2 on 2026-02-13 12:05

import laundries.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundries', '0002_openinghours_laundry_laundries_l_is_feat_fc6373_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundry',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laundry',
            name='deactivation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='laundries/', validators=[laundries.utils.validators.validate_file_upload], verbose_name='image'),
        ),
    ]
