# Generated by Django 6.0.2 on 2026-03-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laundries", "0005_laundry_min_order"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="laundry",
            name="laundries_l_latitud_13d2ca_idx",
        ),
        migrations.AddField(
            model_name="laundry",
            name="city",
            field=models.CharField(
                db_index=True, default="Accra", max_length=100, verbose_name="city"
            ),
        ),
    ]
