# Generated by Django 6.0.2 on 2026-03-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laundries", "0007_laundry_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SERVICE_TYPE", "Service Type"),
                    ("ITEM_CATEGORY", "Item Category"),
                ],
                db_index=True,
                default="SERVICE_TYPE",
                max_length=20,
                null=True,
                verbose_name="type",
            ),
        ),
    ]
