# Generated by Django 6.0.4 on 2026-06-10 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundries', '0009_laundry_pickup_fee_alter_category_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('laundry', 'user'), name='unique_review_per_user_per_laundry'),
        ),
    ]
