# Generated by Django 6.0.3 on 2026-03-25 15:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundries', '0009_laundry_pickup_fee_alter_category_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='invite email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='invite phone')),
                ('name', models.CharField(max_length=150, verbose_name='staff name')),
                ('role', models.CharField(choices=[('MANAGER', 'Manager'), ('WASHER', 'Washer'), ('IRONER', 'Ironer'), ('DRIVER', 'Driver'), ('RECEPTIONIST', 'Receptionist')], default='WASHER', max_length=20, verbose_name='role')),
                ('invite_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=20, verbose_name='invite status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laundry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='laundries.laundry')),
                ('user', models.ForeignKey(blank=True, help_text='Linked user account (set when invite is accepted)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Laundry Staff',
                'verbose_name_plural': 'Laundry Staff',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['laundry', 'role'], name='laundries_l_laundry_ece6a8_idx')],
                'unique_together': {('laundry', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g. 'Washer #1', 'Samsung Dryer'", max_length=100, verbose_name='machine name')),
                ('machine_type', models.CharField(choices=[('WASHER', 'Washing Machine'), ('DRYER', 'Dryer'), ('IRONER', 'Ironing Press'), ('OTHER', 'Other')], default='WASHER', max_length=20, verbose_name='type')),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('BUSY', 'In Use'), ('MAINTENANCE', 'Under Maintenance'), ('OUT_OF_ORDER', 'Out of Order')], default='IDLE', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, help_text='Maintenance notes or special instructions', verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laundry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='laundries.laundry')),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['laundry', 'status'], name='laundries_m_laundry_9925ac_idx')],
            },
        ),
    ]
