# Generated by Django 6.0.3 on 2026-03-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundries', '0010_laundrystaff_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundry',
            name='min_weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='minimum weight'),
        ),
        migrations.AddField(
            model_name='laundry',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='price per kg'),
        ),
        migrations.AddField(
            model_name='laundry',
            name='pricing_methods',
            field=models.JSONField(blank=True, default=list, help_text="List of supported methods: ['PER_ITEM', 'PER_KG']", verbose_name='pricing methods'),
        ),
    ]
