# Generated by Django 6.0.6 on 2026-06-13 15:13

import django.core.validators
import django.db.models.deletion
import laundries.utils.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundries', '0010_review_unique_review_per_user_per_laundry'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundry',
            name='pricing_model',
            field=models.CharField(choices=[('BY_ITEM', 'Per item / garment count'), ('BY_WEIGHT', 'Per weight (kg)'), ('HYBRID', 'Hybrid (item + weight)')], db_index=True, default='BY_ITEM', max_length=10, verbose_name='pricing model'),
        ),
        migrations.AddField(
            model_name='openinghours',
            name='is_overnight',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='latitude',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=9, validators=[laundries.utils.validators.validate_latitude], verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='longitude',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=9, validators=[laundries.utils.validators.validate_longitude], verbose_name='longitude'),
        ),
        migrations.CreateModel(
            name='LaundryWeightPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_price_per_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='base price per kg')),
                ('minimum_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='minimum charge')),
                ('minimum_order_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='minimum order weight (kg)')),
                ('rounding_strategy', models.CharField(choices=[('NONE', 'No rounding'), ('UP_0_5_KG', 'Round up to nearest 0.5 kg'), ('UP_1_KG', 'Round up to nearest 1 kg')], default='NONE', max_length=12, verbose_name='rounding strategy')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laundry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weight_pricing', to='laundries.laundry')),
            ],
            options={
                'verbose_name': 'Laundry Weight Pricing',
                'verbose_name_plural': 'Laundry Weight Pricing',
            },
        ),
        migrations.CreateModel(
            name='PriceListImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_image', models.ImageField(upload_to='price_imports/', validators=[laundries.utils.validators.validate_file_upload], verbose_name='source image')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('READY', 'Ready for review'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=12)),
                ('provider', models.CharField(blank=True, default='', max_length=40)),
                ('error', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('laundry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_import_jobs', to='laundries.laundry')),
            ],
            options={
                'verbose_name': 'Price List Import Job',
                'verbose_name_plural': 'Price List Import Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceListDraftItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=120)),
                ('suggested_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=80)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('is_selected', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_items', to='laundries.pricelistimportjob')),
            ],
            options={
                'verbose_name': 'Price List Draft Item',
                'verbose_name_plural': 'Price List Draft Items',
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='LaundryPricingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=120, verbose_name='item name')),
                ('category', models.CharField(blank=True, default='', max_length=80, verbose_name='category')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pricing_items/', validators=[laundries.utils.validators.validate_file_upload], verbose_name='image')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='unit price')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laundry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_items', to='laundries.laundry')),
            ],
            options={
                'verbose_name': 'Laundry Pricing Item',
                'verbose_name_plural': 'Laundry Pricing Items',
                'ordering': ['display_order', 'item_name'],
                'indexes': [models.Index(fields=['laundry', 'is_active'], name='laundries_l_laundry_b199d2_idx'), models.Index(fields=['laundry', 'display_order'], name='laundries_l_laundry_eb1bd6_idx')],
                'unique_together': {('laundry', 'item_name')},
            },
        ),
        migrations.AddIndex(
            model_name='pricelistimportjob',
            index=models.Index(fields=['laundry', 'status'], name='laundries_p_laundry_a5265e_idx'),
        ),
    ]
