# Generated by Django 6.0.5 on 2026-06-13 16:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundries', '0011_laundry_pricing_model_openinghours_is_overnight_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='laundry',
            name='ironing_available',
            field=models.BooleanField(db_index=True, default=False, verbose_name='ironing available'),
        ),
        migrations.AddField(
            model_name='laundry',
            name='is_eco_friendly',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is eco-friendly'),
        ),
        migrations.AddField(
            model_name='laundry',
            name='service_area_polygon',
            field=models.JSONField(blank=True, null=True, verbose_name='service area polygon'),
        ),
        migrations.AddField(
            model_name='laundry',
            name='service_radius_km',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='service radius (km)'),
        ),
        migrations.AddField(
            model_name='laundry',
            name='vacation_mode',
            field=models.BooleanField(db_index=True, default=False, verbose_name='vacation mode'),
        ),
        migrations.CreateModel(
            name='DeliveryZonePricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_distance_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_distance_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pickup_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('laundry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_zones', to='laundries.laundry')),
            ],
            options={
                'verbose_name': 'Delivery Zone Pricing',
                'verbose_name_plural': 'Delivery Zone Pricing',
                'ordering': ['min_distance_km'],
            },
        ),
        migrations.CreateModel(
            name='OwnerAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=100, verbose_name='action')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='details')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laundry_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('laundry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='laundries.laundry')),
            ],
            options={
                'verbose_name': 'Owner Audit Log',
                'verbose_name_plural': 'Owner Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledPriceChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_at', models.DateTimeField(db_index=True)),
                ('pricing_data', models.JSONField()),
                ('is_applied', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('laundry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_price_changes', to='laundries.laundry')),
            ],
            options={
                'verbose_name': 'Scheduled Price Change',
                'verbose_name_plural': 'Scheduled Price Changes',
                'ordering': ['effective_at'],
            },
        ),
        migrations.CreateModel(
            name='HolidayOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('laundry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_overrides', to='laundries.laundry')),
            ],
            options={
                'verbose_name': 'Holiday Override',
                'verbose_name_plural': 'Holiday Overrides',
                'ordering': ['date'],
                'unique_together': {('laundry', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PricingCatalogVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('items_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('laundry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_versions', to='laundries.laundry')),
            ],
            options={
                'verbose_name': 'Pricing Catalog Version',
                'verbose_name_plural': 'Pricing Catalog Versions',
                'ordering': ['-version_number'],
                'unique_together': {('laundry', 'version_number')},
            },
        ),
    ]
