# Generated by Django 6.0.7 on 2026-07-14 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundries', '0012_laundry_ironing_available_laundry_is_eco_friendly_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='laundry',
            name='changes_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laundry',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_laundries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laundry',
            name='status_reason',
            field=models.TextField(blank=True, default='', verbose_name='status reason'),
        ),
        migrations.AddField(
            model_name='laundry',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CHANGES_REQUESTED', 'Changes Requested'), ('SUSPENDED', 'Suspended')], db_index=True, default='PENDING', max_length=20, verbose_name='approval status'),
        ),
    ]
