# Generated by Django 6.0.7 on 2026-07-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundries', '0013_laundry_changes_requested_at_laundry_reviewed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundry',
            name='paystack_subaccount_code',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='paystack subaccount code'),
        ),
        migrations.AddField(
            model_name='laundry',
            name='split_payments_enabled',
            field=models.BooleanField(db_index=True, default=False, verbose_name='settle payments directly'),
        ),
    ]
