# Generated by Django 6.0.5 on 2026-09-24 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundries', '0016_laundry_paystack_recipient_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='laundry',
            name='payout_account_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='payout account name'),
        ),
        migrations.AddField(
            model_name='laundry',
            name='payout_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laundry',
            name='payout_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payout_laundries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laundry',
            name='payout_failure_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='laundry',
            name='payout_method',
            field=models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('BANK_ACCOUNT', 'Bank Account')], default='MOBILE_MONEY', max_length=20, verbose_name='payout method'),
        ),
        migrations.AddField(
            model_name='laundry',
            name='payout_phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='payout phone display'),
        ),
        migrations.AddField(
            model_name='laundry',
            name='payout_phone_normalized',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='payout phone normalized'),
        ),
        migrations.AddField(
            model_name='laundry',
            name='payout_provider',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='payout provider'),
        ),
        migrations.AddField(
            model_name='laundry',
            name='payout_status',
            field=models.CharField(choices=[('PAYOUT_SETUP_REQUIRED', 'Payout Setup Required'), ('PAYOUT_SETUP_PENDING', 'Payout Setup Pending'), ('PAYOUT_READY', 'Payout Ready'), ('PAYOUT_FAILED_RETRYABLE', 'Payout Failed Retryable')], db_index=True, default='PAYOUT_SETUP_REQUIRED', max_length=30, verbose_name='payout status'),
        ),
        migrations.AddField(
            model_name='laundry',
            name='recipient_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
