# Generated by Django 6.0.7 on 2026-09-25 09:47

import django.db.models.deletion
import laundries.utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundries', '0017_laundry_payout_account_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricelistdraftitem',
            options={'ordering': ['position', 'item_name'], 'verbose_name': 'Price List Draft Item', 'verbose_name_plural': 'Price List Draft Items'},
        ),
        migrations.AddField(
            model_name='pricelistdraftitem',
            name='match_type',
            field=models.CharField(choices=[('NONE', 'New'), ('EXACT', 'Same name exists'), ('POSSIBLE', 'Possible match')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='pricelistdraftitem',
            name='matched_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='laundries.laundrypricingitem'),
        ),
        migrations.AddField(
            model_name='pricelistdraftitem',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pricelistdraftitem',
            name='price_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pricelistdraftitem',
            name='pricing_method',
            field=models.CharField(choices=[('PER_ITEM', 'Per item'), ('PER_KG', 'Per kg'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10),
        ),
        migrations.AddField(
            model_name='pricelistdraftitem',
            name='raw_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pricelistdraftitem',
            name='review_state',
            field=models.CharField(choices=[('LOOKS_GOOD', 'Looks good'), ('CHECK', 'Please check'), ('UNREADABLE', 'Could not read')], default='CHECK', max_length=12),
        ),
        migrations.AddField(
            model_name='pricelistdraftitem',
            name='source_text',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='pricelistdraftitem',
            name='surcharge_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pricelistdraftitem',
            name='surcharge_type',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='pricelistdraftitem',
            name='variant',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='pricelistdraftitem',
            name='warnings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pricelistimportjob',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricelistimportjob',
            name='confirm_result',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pricelistimportjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_import_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricelistimportjob',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='pricelistimportjob',
            name='document_warnings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pricelistimportjob',
            name='error_code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='pricelistimportjob',
            name='image_sha256',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='pricelistimportjob',
            name='latency_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricelistimportjob',
            name='model_name',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='pricelistimportjob',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='pricelistimportjob',
            name='provider_trace',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pricelistimportjob',
            name='result',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pricelistimportjob',
            name='served_from_cache',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pricelistimportjob',
            name='laundry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_import_jobs', to='laundries.laundry'),
        ),
        migrations.AlterField(
            model_name='pricelistimportjob',
            name='source_image',
            field=models.ImageField(blank=True, upload_to='price_imports/', validators=[laundries.utils.validators.validate_file_upload], verbose_name='source image'),
        ),
        migrations.AlterField(
            model_name='pricelistimportjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('READY', 'Ready for review'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=12),
        ),
        migrations.AddIndex(
            model_name='pricelistimportjob',
            index=models.Index(fields=['laundry', 'image_sha256'], name='laundries_p_laundry_1973f6_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelistimportjob',
            index=models.Index(fields=['created_at'], name='laundries_p_created_b32388_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelistimportjob',
            index=models.Index(fields=['created_by', 'image_sha256'], name='laundries_p_created_53e309_idx'),
        ),
    ]
