# Generated by Django 6.0.5 on 2026-09-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundries', '0018_price_list_ai_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundry',
            name='free_delivery_promo_enabled',
            field=models.BooleanField(db_index=True, default=False, help_text='Toggle ON to offer free pickup and delivery to customers.', verbose_name='free pickup & delivery promo enabled'),
        ),
        migrations.AddField(
            model_name='laundry',
            name='promo_end_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='promo end date/time'),
        ),
        migrations.AddField(
            model_name='laundry',
            name='promo_funding_source',
            field=models.CharField(choices=[('LAUNDRY', 'Laundry Funded'), ('PLATFORM', 'Platform Funded')], default='LAUNDRY', help_text='Who funds the rider logistics subsidy for this promo.', max_length=20, verbose_name='promo funding source'),
        ),
        migrations.AddField(
            model_name='laundry',
            name='promo_max_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional distance ceiling for free delivery (null = up to laundry service radius).', max_digits=6, null=True, verbose_name='promo maximum distance (km)'),
        ),
        migrations.AddField(
            model_name='laundry',
            name='promo_start_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='promo start date/time'),
        ),
    ]
