# Generated by Django 6.0.7 on 2026-09-25 18:34

from django.db import migrations, models



def platform_to_simame(apps, schema_editor):
    Laundry = apps.get_model('laundries', 'Laundry')
    Laundry.objects.filter(promo_funding_source='PLATFORM').update(promo_funding_source='SIMAME')


def simame_to_platform(apps, schema_editor):
    Laundry = apps.get_model('laundries', 'Laundry')
    Laundry.objects.filter(promo_funding_source='SIMAME').update(promo_funding_source='PLATFORM')


class Migration(migrations.Migration):

    dependencies = [
        ('laundries', '0019_laundry_free_delivery_promo_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundry',
            name='promo_campaign_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='laundry',
            name='promo_last_notified_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='laundry',
            name='promo_min_order_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Orders whose items total is below this pay normal transport.', max_digits=10, null=True, verbose_name='promo minimum order (GHS)'),
        ),
        migrations.AddField(
            model_name='laundry',
            name='promo_name',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='promo name'),
        ),
        migrations.AddField(
            model_name='laundry',
            name='promo_notified_campaign_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='laundry',
            name='promo_scope',
            field=models.CharField(choices=[('PICKUP_AND_DELIVERY', 'Free pickup & delivery'), ('PICKUP_ONLY', 'Free pickup only'), ('DELIVERY_ONLY', 'Free delivery only')], default='PICKUP_AND_DELIVERY', max_length=24, verbose_name='promo covers'),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='promo_funding_source',
            field=models.CharField(choices=[('LAUNDRY', 'Laundry funded (deducted from laundry payout)'), ('SIMAME', 'Simame funded (platform promotional cost)')], default='LAUNDRY', help_text='Who pays the rider for the transport the customer gets free. Owners can only choose laundry funded.', max_length=20, verbose_name='promo funding source'),
        ),
        migrations.RunPython(platform_to_simame, simame_to_platform),
    ]
