# Generated by Django 6.0.5 on 2026-10-03 04:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundries', '0020_laundry_promo_campaign_id_and_more'),
        ('ordering', '0020_order_logistics_nominal_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='laundry',
            index=models.Index(fields=['status', 'is_active', '-created_at'], name='laundries_l_status_95998a_idx'),
        ),
        migrations.AddIndex(
            model_name='laundry',
            index=models.Index(fields=['status', 'is_active', 'is_featured'], name='laundries_l_status_5abe9d_idx'),
        ),
        migrations.AddIndex(
            model_name='laundryservice',
            index=models.Index(fields=['laundry', 'is_available', 'price'], name='laundries_l_laundry_cf4d0c_idx'),
        ),
    ]
